version: '2'
services:
  core:
    image: odaniait/odania-core
    links:
      - consul
    depends_on:
      - consul
    volumes:
      - ./fixtures/static/data:/srv/static
      - ./fixtures/static/config:/srv/config
    environment:
      ENVIRONMENT: development
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    tty: true
    stdin_open: true
  varnish:
    image: odaniait/odania-varnish
    links:
      - consul
    depends_on:
      - consul
      - core
    environment:
      ENVIRONMENT: development
    tty: true
    stdin_open: true

  consulmaster:
    image: odaniait/docker-consul:latest
    environment:
      BOOTSTRAP_EXPECT: 1
      GOMAXPROCS: 2
    tty: true
    stdin_open: true
  consul:
    image: odaniait/docker-consul:latest
    environment:
      GOMAXPROCS: 2
    links:
      - consulmaster
    depends_on:
      - consulmaster
    tty: true
    stdin_open: true
  elasticsearch:
    image: elasticsearch:2.3
    tty: true
    stdin_open: true


  odania-static:
    image: odaniait/odania-static
    links:
      - consul
    volumes:
      - ./static-content:/srv/static
    tty: true
    stdin_open: true

  odania-admin:
    image: odaniait/odania-admin
    links:
      - consul
    volumes:
      - ./config/odania-admin:/srv/config
    tty: true
    stdin_open: true
